= findmax(1)
{project-author} <{project-email}>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: User Commands
:mansource: findmax
:man-linkstyle: blue R <>
:nofooter:

== NAME

findmax - schnelles Dateisuchwerkzeug für Maximalwert-Abfragen

== SYNOPSIS

*findmax* [_OPTIONS_] [_FILE_...]

== DESCRIPTION

*findmax* ist ein schnelles Dateisuchwerkzeug, optimiert für O(1)-Abfragen nach Maximalwerten. Sortierung nach Änderungs-, Zugriffs- oder Erstellungszeit, Größe oder Name, mit Formatierung und Filtern.

== OPTIONS

*-R*, *--recursive*::
  Rekursiv in Verzeichnisse suchen.
*-r*, *--reverse*::
  In umgekehrter Reihenfolge sortieren (älteste/kleinste zuerst).
*-u*::
  Nach Zugriffszeit (atime) sortieren.
*-c*::
  Nach Metadaten-Änderungszeit (ctime) sortieren.
*-t*::
  Nach Änderungszeit (mtime) sortieren. Dies ist die Voreinstellung.
*-S*::
  Nach Dateigröße sortieren.
*-n*, *--name*::
  Nach Dateiname gemäß aktueller Locale sortieren.
*-f*, *--file-only*::
  Nur reguläre Dateien anzeigen.
*-d*, *--dir-only*::
  Nur Verzeichnisse anzeigen.
*-L*, *--dereference*::
  Symbolischen Links folgen (stat() statt lstat()).
*-F*, *--format* _FMT_::
  Benutzerdefiniertes Ausgabeformat verwenden. Siehe Abschnitt FORMAT.
*-_NUM_*::
  Die ersten NUM Dateien anzeigen statt nur 1 (Standard).
*-v*, *--verbose*::
  Wiederholen für ausführlichere Protokolle.
*-q*, *--quiet*::
  Weniger Meldungen anzeigen und nicht fatale Fehler unterdrücken.
**--time**=__WORD__::
  Zeitstempel für die Sortierung wählen:
  +
  *atime*, *access*, *use*;;
    Zugriffszeit
  *ctime*, *status*;;
    Metadaten-Änderungszeit
  *mtime*, *modification*;;
    Änderungszeit (Standard)
  *birth*, *creation*;;
    Erstellungszeit (falls unterstützt)
**--maxdepth**=__NUM__::
  Verzeichnistiefe auf NUM Ebenen begrenzen.
*-h*, *--help*::
  Diese Hilfe anzeigen und beenden.
*--version*::
  Versionsinformationen anzeigen und beenden.

== FORMAT

The format string supports the following specifiers:

=== File Information

*%n*::
  File name
*%N*::
  Quoted file name with dereference if symbolic link
*%s*::
  Total size in bytes
*%F*::
  File type (regular file, directory, etc.)
*%f*::
  Raw mode in hexadecimal
*%a*::
  Permission bits in octal
*%A*::
  Permission bits and file type in human readable form

=== Ownership

*%u*::
  User ID of owner
*%U*::
  User name of owner
*%g*::
  Group ID of owner
*%G*::
  Group name of owner

=== Timestamps

*%x*::
  Time of last access, human-readable
*%X*::
  Time of last access, seconds since Epoch
*%y*::
  Time of last data modification, human-readable
*%Y*::
  Time of last data modification, seconds since Epoch
*%z*::
  Time of last status change, human-readable
*%Z*::
  Time of last status change, seconds since Epoch
*%w*::
  Time of file birth, human-readable (- if unknown)
*%W*::
  Time of file birth, seconds since Epoch (0 if unknown)

=== System Information

*%d*::
  Device number in decimal
*%D*::
  Device number in hexadecimal
*%i*::
  Inode number
*%h*::
  Number of hard links
*%b*::
  Number of blocks allocated
*%B*::
  Size in bytes of each block (usually 512)

== EXAMPLES

Find the most recently modified file in current directory:::
  *findmax -t .*
Find the oldest file recursively with timestamp:::
  *findmax -r -t -R -F %n %y /home/user*
Find the 5 largest files:::
  *findmax -S -R -5 /var/log*
Find newest regular file only:::
  *findmax -t -f -R /etc*
Find files with detailed information:::
  *findmax -t -F %n (%s bytes) %U:%G %y /tmp*
Limit search depth to 2 levels:::
  *findmax -t -R --maxdepth=2 /usr/share*

== PERFORMANCE

*findmax* verwendet einen Min-Heap, um nur die Top-N-Ergebnisse zu halten, ohne alle Dateien zu sortieren. Typische Fälle erreichen nahezu O(1).

== EXIT STATUS

*0*::
  Erfolg
*1*::
  Allgemeiner Fehler (ungültige Argumente, Zugriffsfehler usw.)

== AUTHOR

Geschrieben von Lenik <findmax@bodz.net>.

== COPYRIGHT

Copyright (C) 2026 Lenik. Dies ist freie Software; siehe den Quelltext für Kopierbedingungen. Es gibt KEINE Gewährleistung.

== SEE ALSO

*find*(1), *ls*(1), *stat*(1), *locate*(1)
