= findmax(1)
{project-author} <{project-email}>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: User Commands
:mansource: findmax
:man-linkstyle: blue R <>
:nofooter:

== NAME

findmax - أداة سريعة للبحث عن الملفات محسّنة لاستعلامات القيمة القصوى

== SYNOPSIS

*findmax* [_OPTIONS_] [_FILE_...]

== DESCRIPTION

*findmax* أداة سريعة للبحث عن الملفات محسّنة لاستعلامات O(1) لإيجاد القيم القصوى وفق معايير محددة. يمكن الاعتماد على وقت التعديل أو الوصول أو الإنشاء أو الحجم أو الاسم، مع تنسيق وفلاتر.

== OPTIONS

*-R*, *--recursive*::
  البحث بشكل متكرر في المجلدات.
*-r*, *--reverse*::
  الترتيب عكسياً (الأقدم/الأصغر أولاً).
*-u*::
  الترتيب حسب وقت الوصول (atime).
*-c*::
  الترتيب حسب وقت تغيير البيانات الوصفية (ctime).
*-t*::
  الترتيب حسب وقت التعديل (mtime). هذا هو الافتراضي.
*-S*::
  الترتيب حسب حجم الملف.
*-n*, *--name*::
  الترتيب حسب اسم الملف وفق الإعدادات المحلية الحالية.
*-f*, *--file-only*::
  إظهار الملفات العادية فقط.
*-d*, *--dir-only*::
  إظهار المجلدات فقط.
*-L*, *--dereference*::
  اتباع الروابط الرمزية (استخدام stat() بدلاً من lstat()).
*-F*, *--format* _FMT_::
  استخدام تنسيق إخراج مخصص. انظر قسم FORMAT.
*-_NUM_*::
  إظهار أول NUM ملفات بدلاً من 1 (الافتراضي).
*-v*, *--verbose*::
  كرر للحصول على سجلات أكثر تفصيلاً.
*-q*, *--quiet*::
  إظهار رسائل أقل وكتم الأخطاء غير القاتلة.
**--time**=__WORD__::
  اختر الختم الزمني المستخدم للترتيب:
  +
  *atime*, *access*, *use*;;
    وقت الوصول
  *ctime*, *status*;;
    وقت تغيير البيانات الوصفية
  *mtime*, *modification*;;
    وقت التعديل (افتراضي)
  *birth*, *creation*;;
    وقت الإنشاء (إن وُجد الدعم)
**--maxdepth**=__NUM__::
  تقييد عمق اجتياز المجلدات إلى NUM مستويات.
*-h*, *--help*::
  عرض هذه المساعدة والخروج.
*--version*::
  عرض معلومات الإصدار والخروج.

== FORMAT

The format string supports the following specifiers:

=== File Information

*%n*::
  File name
*%N*::
  Quoted file name with dereference if symbolic link
*%s*::
  Total size in bytes
*%F*::
  File type (regular file, directory, etc.)
*%f*::
  Raw mode in hexadecimal
*%a*::
  Permission bits in octal
*%A*::
  Permission bits and file type in human readable form

=== Ownership

*%u*::
  User ID of owner
*%U*::
  User name of owner
*%g*::
  Group ID of owner
*%G*::
  Group name of owner

=== Timestamps

*%x*::
  Time of last access, human-readable
*%X*::
  Time of last access, seconds since Epoch
*%y*::
  Time of last data modification, human-readable
*%Y*::
  Time of last data modification, seconds since Epoch
*%z*::
  Time of last status change, human-readable
*%Z*::
  Time of last status change, seconds since Epoch
*%w*::
  Time of file birth, human-readable (- if unknown)
*%W*::
  Time of file birth, seconds since Epoch (0 if unknown)

=== System Information

*%d*::
  Device number in decimal
*%D*::
  Device number in hexadecimal
*%i*::
  Inode number
*%h*::
  Number of hard links
*%b*::
  Number of blocks allocated
*%B*::
  Size in bytes of each block (usually 512)

== EXAMPLES

Find the most recently modified file in current directory:::
  *findmax -t .*
Find the oldest file recursively with timestamp:::
  *findmax -r -t -R -F %n %y /home/user*
Find the 5 largest files:::
  *findmax -S -R -5 /var/log*
Find newest regular file only:::
  *findmax -t -f -R /etc*
Find files with detailed information:::
  *findmax -t -F %n (%s bytes) %U:%G %y /tmp*
Limit search depth to 2 levels:::
  *findmax -t -R --maxdepth=2 /usr/share*

== PERFORMANCE

يستخدم *findmax* كومة صغرى للاحتفاظ بأفضل N نتائج فقط، متجنباً فرز كل الملفات عند الحاجة للقيم القصوى فقط. في الحالات النموذجية يقترب الأداء من O(1).

== EXIT STATUS

*0*::
  نجاح
*1*::
  خطأ عام (وسائط غير صالحة، أخطاء وصول، إلخ)

== AUTHOR

كتبه Lenik <findmax@bodz.net>.

== COPYRIGHT

Copyright (C) 2026 Lenik. هذا برنامج حر؛ انظر المصدر لشروط النسخ. لا توجد أي ضمانة.

== SEE ALSO

*find*(1), *ls*(1), *stat*(1), *locate*(1)
