= findmax(1)
{project-author} <{project-email}>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: User Commands
:mansource: findmax
:man-linkstyle: blue R <>
:nofooter:

== NAME

findmax - 최댓값 질의에 최적화된 빠른 파일 찾기 유틸리티

== SYNOPSIS

*findmax* [_OPTIONS_] [_FILE_...]

== DESCRIPTION

*findmax*는 지정 조건의 최댓값 파일을 찾기 위한 빠른 유틸리티로, O(1) 질의에 최적화되어 있습니다. 수정/접근/생성 시간, 크기, 이름으로 찾을 수 있으며 출력 형식과 필터를 지원합니다.

== OPTIONS

*-R*, *--recursive*::
  디렉터리를 재귀적으로 검색합니다.
*-r*, *--reverse*::
  역순으로 정렬합니다(가장 오래됨/작음 우선).
*-u*::
  접근 시간(atime)으로 정렬합니다.
*-c*::
  메타데이터 변경 시간(ctime)으로 정렬합니다.
*-t*::
  수정 시간(mtime)으로 정렬합니다. 이것이 기본값입니다.
*-S*::
  파일 크기로 정렬합니다.
*-n*, *--name*::
  현재 로케일 설정으로 파일 이름순 정렬합니다.
*-f*, *--file-only*::
  일반 파일만 표시합니다.
*-d*, *--dir-only*::
  디렉터리만 표시합니다.
*-L*, *--dereference*::
  심볼릭 링크를 따릅니다(lstat() 대신 stat()).
*-F*, *--format* _FMT_::
  사용자 지정 출력 형식을 사용합니다. FORMAT 절을 참고하세요.
*-_NUM_*::
  기본 1개가 아니라 상위 NUM개를 표시합니다.
*-v*, *--verbose*::
  반복하면 로그가 더 상세해집니다.
*-q*, *--quiet*::
  로그를 줄이고 치명적이지 않은 오류를 숨깁니다.
**--time**=__WORD__::
  정렬에 사용할 타임스탬프를 선택합니다:
  +
  *atime*, *access*, *use*;;
    접근 시간
  *ctime*, *status*;;
    메타데이터 변경 시간
  *mtime*, *modification*;;
    수정 시간(기본)
  *birth*, *creation*;;
    생성 시간(지원 시)
**--maxdepth**=__NUM__::
  디렉터리 탐색 깊이를 NUM으로 제한합니다.
*-h*, *--help*::
  이 도움말을 표시하고 종료합니다.
*--version*::
  버전 정보를 표시하고 종료합니다.

== FORMAT

The format string supports the following specifiers:

=== File Information

*%n*::
  File name
*%N*::
  Quoted file name with dereference if symbolic link
*%s*::
  Total size in bytes
*%F*::
  File type (regular file, directory, etc.)
*%f*::
  Raw mode in hexadecimal
*%a*::
  Permission bits in octal
*%A*::
  Permission bits and file type in human readable form

=== Ownership

*%u*::
  User ID of owner
*%U*::
  User name of owner
*%g*::
  Group ID of owner
*%G*::
  Group name of owner

=== Timestamps

*%x*::
  Time of last access, human-readable
*%X*::
  Time of last access, seconds since Epoch
*%y*::
  Time of last data modification, human-readable
*%Y*::
  Time of last data modification, seconds since Epoch
*%z*::
  Time of last status change, human-readable
*%Z*::
  Time of last status change, seconds since Epoch
*%w*::
  Time of file birth, human-readable (- if unknown)
*%W*::
  Time of file birth, seconds since Epoch (0 if unknown)

=== System Information

*%d*::
  Device number in decimal
*%D*::
  Device number in hexadecimal
*%i*::
  Inode number
*%h*::
  Number of hard links
*%b*::
  Number of blocks allocated
*%B*::
  Size in bytes of each block (usually 512)

== EXAMPLES

Find the most recently modified file in current directory:::
  *findmax -t .*
Find the oldest file recursively with timestamp:::
  *findmax -r -t -R -F %n %y /home/user*
Find the 5 largest files:::
  *findmax -S -R -5 /var/log*
Find newest regular file only:::
  *findmax -t -f -R /etc*
Find files with detailed information:::
  *findmax -t -F %n (%s bytes) %U:%G %y /tmp*
Limit search depth to 2 levels:::
  *findmax -t -R --maxdepth=2 /usr/share*

== PERFORMANCE

*findmax*는 최소 힙으로 상위 N개만 유지하여 최댓값만 필요할 때 전체 정렬을 피합니다. 일반적인 사용에서 거의 O(1) 성능을 제공합니다.

== EXIT STATUS

*0*::
  성공
*1*::
  일반 오류(잘못된 인수, 파일 접근 오류 등)

== AUTHOR

Lenik <findmax@bodz.net>이(가) 작성했습니다.

== COPYRIGHT

Copyright (C) 2026 Lenik. 이것은 자유 소프트웨어입니다. 복사 조건은 소스를 참고하세요. 보증은 없습니다.

== SEE ALSO

*find*(1), *ls*(1), *stat*(1), *locate*(1)
