= findmax(1)
{project-author} <{project-email}>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: User Commands
:mansource: findmax
:man-linkstyle: blue R <>
:nofooter:

== NAME

findmax - utilidad rápida para buscar archivos optimizada para valores máximos

== SYNOPSIS

*findmax* [_OPTIONS_] [_FILE_...]

== DESCRIPTION

*findmax* es una utilidad rápida para buscar archivos, optimizada para consultas O(1) de valores máximos. Puede basarse en modificación, acceso, creación, tamaño o nombre, con formato y filtros.

== OPTIONS

*-R*, *--recursive*::
  Buscar recursivamente en directorios.
*-r*, *--reverse*::
  Ordenar en orden inverso (más antiguo/pequeño primero).
*-u*::
  Ordenar por hora de acceso (atime).
*-c*::
  Ordenar por hora de cambio de metadatos (ctime).
*-t*::
  Ordenar por hora de modificación (mtime). Este es el valor predeterminado.
*-S*::
  Ordenar por tamaño de archivo.
*-n*, *--name*::
  Ordenar por nombre según la configuración regional.
*-f*, *--file-only*::
  Mostrar solo archivos normales.
*-d*, *--dir-only*::
  Mostrar solo directorios.
*-L*, *--dereference*::
  Seguir enlaces simbólicos (usar stat() en lugar de lstat()).
*-F*, *--format* _FMT_::
  Usar formato de salida personalizado. Ver la sección FORMAT.
*-_NUM_*::
  Mostrar los NUM primeros archivos en lugar de 1 (predeterminado).
*-v*, *--verbose*::
  Repetir para registros más detallados.
*-q*, *--quiet*::
  Mostrar menos mensajes y ocultar errores no fatales.
**--time**=__WORD__::
  Elegir la marca de tiempo para ordenar:
  +
  *atime*, *access*, *use*;;
    Hora de acceso
  *ctime*, *status*;;
    Hora de cambio de metadatos
  *mtime*, *modification*;;
    Hora de modificación (predeterminado)
  *birth*, *creation*;;
    Hora de creación (si se admite)
**--maxdepth**=__NUM__::
  Limitar la profundidad a NUM niveles.
*-h*, *--help*::
  Mostrar esta ayuda y salir.
*--version*::
  Mostrar la información de versión y salir.

== FORMAT

The format string supports the following specifiers:

=== File Information

*%n*::
  File name
*%N*::
  Quoted file name with dereference if symbolic link
*%s*::
  Total size in bytes
*%F*::
  File type (regular file, directory, etc.)
*%f*::
  Raw mode in hexadecimal
*%a*::
  Permission bits in octal
*%A*::
  Permission bits and file type in human readable form

=== Ownership

*%u*::
  User ID of owner
*%U*::
  User name of owner
*%g*::
  Group ID of owner
*%G*::
  Group name of owner

=== Timestamps

*%x*::
  Time of last access, human-readable
*%X*::
  Time of last access, seconds since Epoch
*%y*::
  Time of last data modification, human-readable
*%Y*::
  Time of last data modification, seconds since Epoch
*%z*::
  Time of last status change, human-readable
*%Z*::
  Time of last status change, seconds since Epoch
*%w*::
  Time of file birth, human-readable (- if unknown)
*%W*::
  Time of file birth, seconds since Epoch (0 if unknown)

=== System Information

*%d*::
  Device number in decimal
*%D*::
  Device number in hexadecimal
*%i*::
  Inode number
*%h*::
  Number of hard links
*%b*::
  Number of blocks allocated
*%B*::
  Size in bytes of each block (usually 512)

== EXAMPLES

Find the most recently modified file in current directory:::
  *findmax -t .*
Find the oldest file recursively with timestamp:::
  *findmax -r -t -R -F %n %y /home/user*
Find the 5 largest files:::
  *findmax -S -R -5 /var/log*
Find newest regular file only:::
  *findmax -t -f -R /etc*
Find files with detailed information:::
  *findmax -t -F %n (%s bytes) %U:%G %y /tmp*
Limit search depth to 2 levels:::
  *findmax -t -R --maxdepth=2 /usr/share*

== PERFORMANCE

*findmax* usa un montículo mínimo para conservar solo los N mejores resultados, sin ordenar todos los archivos. En casos típicos ofrece rendimiento cercano a O(1).

== EXIT STATUS

*0*::
  Éxito
*1*::
  Error general (argumentos no válidos, errores de acceso, etc.)

== AUTHOR

Escrito por Lenik <findmax@bodz.net>.

== COPYRIGHT

Copyright (C) 2026 Lenik. Este es software libre; vea el código fuente para las condiciones de copia. NO hay garantía.

== SEE ALSO

*find*(1), *ls*(1), *stat*(1), *locate*(1)
