= findmax(1)
{project-author} <{project-email}>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: User Commands
:mansource: findmax
:man-linkstyle: blue R <>
:nofooter:

== NAME

findmax - 面向最大值查询优化的快速文件查找工具

== SYNOPSIS

*findmax* [_OPTIONS_] [_FILE_...]

== DESCRIPTION

*findmax* 是面向“按指定条件查找最大值文件”的快速工具，针对 O(1) 查询做了优化。可按修改/访问/创建时间、大小或名称查找，并支持自定义输出格式与过滤。

== OPTIONS

*-R*, *--recursive*::
  递归搜索目录。
*-r*, *--reverse*::
  反向排序（最旧/最小优先）。
*-u*::
  按访问时间（atime）排序。
*-c*::
  按元数据更改时间（ctime）排序。
*-t*::
  按修改时间（mtime）排序。这是默认值。
*-S*::
  按文件大小排序。
*-n*, *--name*::
  按当前区域设置的文件名排序。
*-f*, *--file-only*::
  仅显示普通文件。
*-d*, *--dir-only*::
  仅显示目录。
*-L*, *--dereference*::
  跟随符号链接（使用 stat() 而非 lstat()）。
*-F*, *--format* _FMT_::
  使用自定义输出格式字符串。详见 FORMAT 一节。
*-_NUM_*::
  显示前 NUM 个文件，而不是默认的 1 个。
*-v*, *--verbose*::
  重复以增加日志详细程度。
*-q*, *--quiet*::
  显示更少日志并抑制非致命错误。
**--time**=__WORD__::
  选择用于排序的时间戳：
  +
  *atime*, *access*, *use*;;
    访问时间
  *ctime*, *status*;;
    元数据更改时间
  *mtime*, *modification*;;
    修改时间（默认）
  *birth*, *creation*;;
    创建时间（若支持）
**--maxdepth**=__NUM__::
  将目录遍历深度限制为 NUM 层。
*-h*, *--help*::
  显示此帮助并退出。
*--version*::
  输出版本信息并退出。

== FORMAT

The format string supports the following specifiers:

=== File Information

*%n*::
  File name
*%N*::
  Quoted file name with dereference if symbolic link
*%s*::
  Total size in bytes
*%F*::
  File type (regular file, directory, etc.)
*%f*::
  Raw mode in hexadecimal
*%a*::
  Permission bits in octal
*%A*::
  Permission bits and file type in human readable form

=== Ownership

*%u*::
  User ID of owner
*%U*::
  User name of owner
*%g*::
  Group ID of owner
*%G*::
  Group name of owner

=== Timestamps

*%x*::
  Time of last access, human-readable
*%X*::
  Time of last access, seconds since Epoch
*%y*::
  Time of last data modification, human-readable
*%Y*::
  Time of last data modification, seconds since Epoch
*%z*::
  Time of last status change, human-readable
*%Z*::
  Time of last status change, seconds since Epoch
*%w*::
  Time of file birth, human-readable (- if unknown)
*%W*::
  Time of file birth, seconds since Epoch (0 if unknown)

=== System Information

*%d*::
  Device number in decimal
*%D*::
  Device number in hexadecimal
*%i*::
  Inode number
*%h*::
  Number of hard links
*%b*::
  Number of blocks allocated
*%B*::
  Size in bytes of each block (usually 512)

== EXAMPLES

Find the most recently modified file in current directory:::
  *findmax -t .*
Find the oldest file recursively with timestamp:::
  *findmax -r -t -R -F %n %y /home/user*
Find the 5 largest files:::
  *findmax -S -R -5 /var/log*
Find newest regular file only:::
  *findmax -t -f -R /etc*
Find files with detailed information:::
  *findmax -t -F %n (%s bytes) %U:%G %y /tmp*
Limit search depth to 2 levels:::
  *findmax -t -R --maxdepth=2 /usr/share*

== PERFORMANCE

*findmax* 使用最小堆只维护前 N 个结果，在只需最大值时无需对全部文件排序，典型场景接近 O(1) 性能。

== EXIT STATUS

*0*::
  成功
*1*::
  一般错误（无效参数、文件访问错误等）

== AUTHOR

由 Lenik <findmax@bodz.net> 编写。

== COPYRIGHT

Copyright (C) 2026 Lenik。这是自由软件；复制条件见源代码。不提供任何担保。

== SEE ALSO

*find*(1), *ls*(1), *stat*(1), *locate*(1)
