= findmax(1)
{project-author} <{project-email}>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: User Commands
:mansource: findmax
:man-linkstyle: blue R <>
:nofooter:

== NAME

findmax - fast file finding utility optimized for maximum value queries

== SYNOPSIS

*findmax* [_OPTIONS_] [_FILE_...]

== DESCRIPTION

*findmax* is a fast file finding utility specifically optimized for O(1) queries to find files with maximum values for specified criteria. It can find files based on modification time, access time, creation time, size, or name, with support for custom output formatting and various filtering options.

== OPTIONS

*-R*, *--recursive*::
  Recursively search into directories.
*-r*, *--reverse*::
  Sort in reverse order (oldest/smallest first).
*-u*::
  Sort by access time (atime).
*-c*::
  Sort by metadata change time (ctime).
*-t*::
  Sort by modification time (mtime). This is the default.
*-S*::
  Sort by file size.
*-n*, *--name*::
  Sort by file name using current locale settings.
*-f*, *--file-only*::
  Show only regular files, exclude directories and special files.
*-d*, *--dir-only*::
  Show only directories, exclude regular files.
*-L*, *--dereference*::
  Follow symbolic links (use stat() instead of lstat()).
*-F*, *--format* _FMT_::
  Use custom output format string. See FORMAT section for details.
*-_NUM_*::
  Show top NUM files instead of just 1 (default).
*-v*, *--verbose*::
  Enable verbose output.
*-q*, *--quiet*::
  Suppress error messages.
**--time**=__WORD__::
  Select which timestamp to use for sorting:
  +
  *atime*, *access*, *use*;;
    Access time
  *ctime*, *status*;;
    Metadata change time
  *mtime*, *modification*;;
    Modification time (default)
  *birth*, *creation*;;
    Birth/creation time (where supported)
**--maxdepth**=__NUM__::
  Limit directory traversal to NUM levels deep.
*--version*::
  Show version information and exit.
*--help*::
  Show help message and exit.

== FORMAT

The format string supports the following specifiers:

=== File Information

*%n*::
  File name
*%N*::
  Quoted file name with dereference if symbolic link
*%s*::
  Total size in bytes
*%F*::
  File type (regular file, directory, etc.)
*%f*::
  Raw mode in hexadecimal
*%a*::
  Permission bits in octal
*%A*::
  Permission bits and file type in human readable form

=== Ownership

*%u*::
  User ID of owner
*%U*::
  User name of owner
*%g*::
  Group ID of owner
*%G*::
  Group name of owner

=== Timestamps

*%x*::
  Time of last access, human-readable
*%X*::
  Time of last access, seconds since Epoch
*%y*::
  Time of last data modification, human-readable
*%Y*::
  Time of last data modification, seconds since Epoch
*%z*::
  Time of last status change, human-readable
*%Z*::
  Time of last status change, seconds since Epoch
*%w*::
  Time of file birth, human-readable (- if unknown)
*%W*::
  Time of file birth, seconds since Epoch (0 if unknown)

=== System Information

*%d*::
  Device number in decimal
*%D*::
  Device number in hexadecimal
*%i*::
  Inode number
*%h*::
  Number of hard links
*%b*::
  Number of blocks allocated
*%B*::
  Size in bytes of each block (usually 512)

== EXAMPLES

Find the most recently modified file in current directory:::
  *findmax -t .*
Find the oldest file recursively with timestamp:::
  *findmax -r -t -R -F %n %y /home/user*
Find the 5 largest files:::
  *findmax -S -R -5 /var/log*
Find newest regular file only:::
  *findmax -t -f -R /etc*
Find files with detailed information:::
  *findmax -t -F %n (%s bytes) %U:%G %y /tmp*
Limit search depth to 2 levels:::
  *findmax -t -R --maxdepth=2 /usr/share*

== PERFORMANCE

*findmax* is optimized for fast queries using a min-heap data structure to maintain only the top N results, avoiding the need to sort all files when only the maximum values are needed. This provides near O(1) performance for typical use cases.

== EXIT STATUS

*0*::
  Success
*1*::
  General error (invalid arguments, file access errors, etc.)

== AUTHOR

Written by Lenik <findmax@bodz.net>.

== COPYRIGHT

Copyright (C) 2026 Lenik. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== SEE ALSO

*find*(1), *ls*(1), *stat*(1), *locate*(1)
