= findmax(1)
{project-author} <{project-email}>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: User Commands
:mansource: findmax
:man-linkstyle: blue R <>
:nofooter:

== NAME

findmax - utilitaire rapide de recherche de fichiers optimisé pour les valeurs maximales

== SYNOPSIS

*findmax* [_OPTIONS_] [_FILE_...]

== DESCRIPTION

*findmax* est un utilitaire rapide de recherche de fichiers, optimisé pour des requêtes O(1) afin de trouver les fichiers aux valeurs maximales selon des critères donnés. Il peut se baser sur l'heure de modification, d'accès, de création, la taille ou le nom, avec formatage personnalisé et filtres.

== OPTIONS

*-R*, *--recursive*::
  Parcourir les répertoires récursivement.
*-r*, *--reverse*::
  Trier dans l'ordre inverse (plus ancien/plus petit d'abord).
*-u*::
  Trier par heure d'accès (atime).
*-c*::
  Trier par heure de changement des métadonnées (ctime).
*-t*::
  Trier par heure de modification (mtime). C'est la valeur par défaut.
*-S*::
  Trier par taille de fichier.
*-n*, *--name*::
  Trier par nom de fichier selon la locale courante.
*-f*, *--file-only*::
  Afficher uniquement les fichiers ordinaires.
*-d*, *--dir-only*::
  Afficher uniquement les répertoires.
*-L*, *--dereference*::
  Suivre les liens symboliques (utiliser stat() au lieu de lstat()).
*-F*, *--format* _FMT_::
  Utiliser une chaîne de format de sortie personnalisée. Voir la section FORMAT.
*-_NUM_*::
  Afficher les NUM premiers fichiers au lieu d'un seul (défaut).
*-v*, *--verbose*::
  Répéter pour des journaux plus détaillés.
*-q*, *--quiet*::
  Afficher moins de messages et masquer les erreurs non fatales.
**--time**=__WORD__::
  Choisir l'horodatage utilisé pour le tri :
  +
  *atime*, *access*, *use*;;
    Heure d'accès
  *ctime*, *status*;;
    Heure de changement des métadonnées
  *mtime*, *modification*;;
    Heure de modification (défaut)
  *birth*, *creation*;;
    Heure de création (si prise en charge)
**--maxdepth**=__NUM__::
  Limiter la profondeur de parcours à NUM niveaux.
*-h*, *--help*::
  Afficher cette aide et quitter.
*--version*::
  Afficher les informations de version et quitter.

== FORMAT

The format string supports the following specifiers:

=== File Information

*%n*::
  File name
*%N*::
  Quoted file name with dereference if symbolic link
*%s*::
  Total size in bytes
*%F*::
  File type (regular file, directory, etc.)
*%f*::
  Raw mode in hexadecimal
*%a*::
  Permission bits in octal
*%A*::
  Permission bits and file type in human readable form

=== Ownership

*%u*::
  User ID of owner
*%U*::
  User name of owner
*%g*::
  Group ID of owner
*%G*::
  Group name of owner

=== Timestamps

*%x*::
  Time of last access, human-readable
*%X*::
  Time of last access, seconds since Epoch
*%y*::
  Time of last data modification, human-readable
*%Y*::
  Time of last data modification, seconds since Epoch
*%z*::
  Time of last status change, human-readable
*%Z*::
  Time of last status change, seconds since Epoch
*%w*::
  Time of file birth, human-readable (- if unknown)
*%W*::
  Time of file birth, seconds since Epoch (0 if unknown)

=== System Information

*%d*::
  Device number in decimal
*%D*::
  Device number in hexadecimal
*%i*::
  Inode number
*%h*::
  Number of hard links
*%b*::
  Number of blocks allocated
*%B*::
  Size in bytes of each block (usually 512)

== EXAMPLES

Find the most recently modified file in current directory:::
  *findmax -t .*
Find the oldest file recursively with timestamp:::
  *findmax -r -t -R -F %n %y /home/user*
Find the 5 largest files:::
  *findmax -S -R -5 /var/log*
Find newest regular file only:::
  *findmax -t -f -R /etc*
Find files with detailed information:::
  *findmax -t -F %n (%s bytes) %U:%G %y /tmp*
Limit search depth to 2 levels:::
  *findmax -t -R --maxdepth=2 /usr/share*

== PERFORMANCE

*findmax* utilise un tas minimum pour ne conserver que les N meilleurs résultats, évitant de trier tous les fichiers lorsque seules les valeurs maximales sont nécessaires. Cela offre des performances proches de O(1) dans les cas typiques.

== EXIT STATUS

*0*::
  Succès
*1*::
  Erreur générale (arguments invalides, erreurs d'accès, etc.)

== AUTHOR

Écrit par Lenik <findmax@bodz.net>.

== COPYRIGHT

Copyright (C) 2026 Lenik. Ceci est un logiciel libre ; voir les sources pour les conditions de copie. Il n'y a AUCUNE garantie.

== SEE ALSO

*find*(1), *ls*(1), *stat*(1), *locate*(1)
