= findmax(1)
{project-author} <{project-email}>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: User Commands
:mansource: findmax
:man-linkstyle: blue R <>
:nofooter:

== NAME

findmax - utilità veloce per trovare file ottimizzata per valori massimi

== SYNOPSIS

*findmax* [_OPTIONS_] [_FILE_...]

== DESCRIPTION

*findmax* è un'utilità veloce per trovare file, ottimizzata per query O(1) sui valori massimi. Può basarsi su modifica, accesso, creazione, dimensione o nome, con formattazione e filtri.

== OPTIONS

*-R*, *--recursive*::
  Cerca ricorsivamente nelle directory.
*-r*, *--reverse*::
  Ordina in ordine inverso (più vecchio/più piccolo per primo).
*-u*::
  Ordina per ora di accesso (atime).
*-c*::
  Ordina per ora di modifica dei metadati (ctime).
*-t*::
  Ordina per ora di modifica (mtime). Questo è il predefinito.
*-S*::
  Ordina per dimensione del file.
*-n*, *--name*::
  Ordina per nome file secondo la locale corrente.
*-f*, *--file-only*::
  Mostra solo file regolari.
*-d*, *--dir-only*::
  Mostra solo directory.
*-L*, *--dereference*::
  Segui i collegamenti simbolici (usa stat() invece di lstat()).
*-F*, *--format* _FMT_::
  Usa una stringa di formato personalizzata. Vedi la sezione FORMAT.
*-_NUM_*::
  Mostra i primi NUM file invece di 1 (predefinito).
*-v*, *--verbose*::
  Ripeti per registrazioni più dettagliate.
*-q*, *--quiet*::
  Mostra meno messaggi e sopprimi errori non fatali.
**--time**=__WORD__::
  Seleziona il timestamp da usare per l'ordinamento:
  +
  *atime*, *access*, *use*;;
    Ora di accesso
  *ctime*, *status*;;
    Ora di modifica dei metadati
  *mtime*, *modification*;;
    Ora di modifica (predefinito)
  *birth*, *creation*;;
    Ora di creazione (se supportata)
**--maxdepth**=__NUM__::
  Limita la profondità di attraversamento a NUM livelli.
*-h*, *--help*::
  Mostra questo aiuto ed esci.
*--version*::
  Mostra le informazioni di versione ed esci.

== FORMAT

The format string supports the following specifiers:

=== File Information

*%n*::
  File name
*%N*::
  Quoted file name with dereference if symbolic link
*%s*::
  Total size in bytes
*%F*::
  File type (regular file, directory, etc.)
*%f*::
  Raw mode in hexadecimal
*%a*::
  Permission bits in octal
*%A*::
  Permission bits and file type in human readable form

=== Ownership

*%u*::
  User ID of owner
*%U*::
  User name of owner
*%g*::
  Group ID of owner
*%G*::
  Group name of owner

=== Timestamps

*%x*::
  Time of last access, human-readable
*%X*::
  Time of last access, seconds since Epoch
*%y*::
  Time of last data modification, human-readable
*%Y*::
  Time of last data modification, seconds since Epoch
*%z*::
  Time of last status change, human-readable
*%Z*::
  Time of last status change, seconds since Epoch
*%w*::
  Time of file birth, human-readable (- if unknown)
*%W*::
  Time of file birth, seconds since Epoch (0 if unknown)

=== System Information

*%d*::
  Device number in decimal
*%D*::
  Device number in hexadecimal
*%i*::
  Inode number
*%h*::
  Number of hard links
*%b*::
  Number of blocks allocated
*%B*::
  Size in bytes of each block (usually 512)

== EXAMPLES

Find the most recently modified file in current directory:::
  *findmax -t .*
Find the oldest file recursively with timestamp:::
  *findmax -r -t -R -F %n %y /home/user*
Find the 5 largest files:::
  *findmax -S -R -5 /var/log*
Find newest regular file only:::
  *findmax -t -f -R /etc*
Find files with detailed information:::
  *findmax -t -F %n (%s bytes) %U:%G %y /tmp*
Limit search depth to 2 levels:::
  *findmax -t -R --maxdepth=2 /usr/share*

== PERFORMANCE

*findmax* usa un min-heap per mantenere solo i primi N risultati, evitando di ordinare tutti i file. Nei casi tipici offre prestazioni vicine a O(1).

== EXIT STATUS

*0*::
  Successo
*1*::
  Errore generale (argomenti non validi, errori di accesso, ecc.)

== AUTHOR

Scritto da Lenik <findmax@bodz.net>.

== COPYRIGHT

Copyright (C) 2026 Lenik. Questo è software libero; vedere il sorgente per le condizioni di copia. Non c'è ALCUNA garanzia.

== SEE ALSO

*find*(1), *ls*(1), *stat*(1), *locate*(1)
